package org.docsim.utils;

import org.docsim.model.AlgorithmResult;
import org.docsim.model.SimilarityResult;

import java.io.*;
import java.util.Map;

/**
 * Exports the analysis result as a formatted plain-text report.
 */
public class ReportExporter {

    /**
     * Write a detailed TXT report to the given file.
     */
    public static void exportTXT(SimilarityResult result, File outFile) throws IOException {
        try (PrintWriter pw = new PrintWriter(new FileWriter(outFile))) {
            pw.println("╔══════════════════════════════════════════════════════════╗");
            pw.println("║      DOCUMENT SIMILARITY ANALYSIS REPORT                ║");
            pw.println("╚══════════════════════════════════════════════════════════╝");
            pw.println();
            pw.println("Analysis Date  : " + result.getTimestamp());
            pw.println("Total Time     : " + result.getTotalTimeMs() + " ms");
            pw.println();
            pw.println("── DOCUMENTS ────────────────────────────────────────────");
            pw.println("Document A     : " + result.getDoc1().getFileName());
            pw.printf ("               : %d tokens  |  %s%n",
                result.getDoc1().getWordCount(),
                result.getDoc1().getFileSizeFormatted());
            pw.println("Document B     : " + result.getDoc2().getFileName());
            pw.printf ("               : %d tokens  |  %s%n",
                result.getDoc2().getWordCount(),
                result.getDoc2().getFileSizeFormatted());
            pw.println();
            pw.println("── FINAL RESULT ─────────────────────────────────────────");
            pw.printf ("Final Score    : %s%n", result.getFinalScorePercent());
            pw.println("Verdict        : " + result.getVerdict());
            pw.println("Formula        : Jaccard×0.20 + RK×0.15 + KMP×0.15 + Cosine×0.20 + Lev×0.15 + TFIDF×0.15");
            pw.println();
            pw.println("── ALGORITHM RESULTS ────────────────────────────────────");
            pw.printf ("%-20s  %-10s  %-12s  %-12s%n",
                "Algorithm", "Score", "Time (ms)", "Time Complexity");
            pw.println("-".repeat(60));
            for (AlgorithmResult ar : result.getAlgorithmResults()) {
                pw.printf("%-20s  %-10s  %-12d  %-12s%n",
                    ar.getAlgorithmName(),
                    ar.getScorePercent(),
                    ar.getExecutionTimeMs(),
                    ar.getTimeComplexity());
            }
            pw.println();
            pw.println("── COMMON KEYWORDS ──────────────────────────────────────");
            if (result.getCommonKeywords() != null) {
                pw.println(String.join(", ", result.getCommonKeywords()));
            }
            pw.println();
            pw.println("── TOP KEYWORDS — Document A ────────────────────────────");
            if (result.getTopKeywordsDoc1() != null) {
                for (Map.Entry<String, Integer> e : result.getTopKeywordsDoc1()) {
                    pw.printf("  %-20s  %d%n", e.getKey(), e.getValue());
                }
            }
            pw.println();
            pw.println("── TOP KEYWORDS — Document B ────────────────────────────");
            if (result.getTopKeywordsDoc2() != null) {
                for (Map.Entry<String, Integer> e : result.getTopKeywordsDoc2()) {
                    pw.printf("  %-20s  %d%n", e.getKey(), e.getValue());
                }
            }
            pw.println();
            pw.println("═".repeat(62));
            pw.println("  Generated by DocSimilarity Pro v2.0");
            pw.println("═".repeat(62));
        }
    }
}
